### PR TITLE
Fix diff functions for access tokens

### LINKED ISSUE #158: Implement Read and Update for team access tokens
Refreshing (and updating) a team access token currently has no effect. We should fix this.

### LINKED ISSUE #159: Calling `pulumiservice.TeamAccessToken()` with `--refresh` causes token name conflict and update failure
### What happened?

When using this provider, a customer can create a Pulumi app to efficiently manage Team Access Tokens.

However, if during a subsequent update `--refresh` is used, Pulumi will attempt to recreate a token that already exists. As a result to this, the update fails with the error `failed to create access token: 409 API error: Conflict: token name already exists` because a token with the same name already exists.

### Expected Behavior

The team access token is create during the 1st deployment, then no further update is needed even when calling `pulumi up --refresh`.

### Steps to reproduce

1. `pulumi new typescript`
2. `npm install --save @pulumi/pulumiservice @pulumi/random`
3. Use the `index.ts` provided below
4. run `pulumi up --yes` and a new team access token is created ✅
5. run `pulumi up --yes` and nothing gets updated ✅
6. run `pulumi up --yes --refresh`, the update attempts to create a new team access token and subsequently fails ❌

### Output of `pulumi about`

```
CLI          
Version      3.77.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME           VERSION
nodejs         unknown
pulumiservice  0.10.1
random         4.13.2

Host     
OS       debian
Version  12.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.17.0'

Current Stack: menfin/pulumiservice-ts/dev

TYPE                                    URN
pulumi:pulumi:Stack                     urn:pulumi:dev::pulumiservice-ts::pulumi:pulumi:Stack::pulumiservice-ts-dev
pulumi:providers:random                 urn:pulumi:dev::pulumiservice-ts::pulumi:providers:random::default_4_13_2
random:index/randomString:RandomString  urn:pulumi:dev::pulumiservice-ts::random:index/randomString:RandomString::[aureq]-pulumi-token-suffix
pulumi:providers:pulumiservice          urn:pulumi:dev::pulumiservice-ts::pulumi:providers:pulumiservice::default_0_10_1


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi

Dependencies:
NAME                   VERSION
@pulumi/random         4.13.2
@types/node            16.18.40
@pulumi/pulumi         3.78.0
@pulumi/pulumiservice  0.10.1

Pulumi locates its logs in /tmp by default
```

### Additional context

```ts
import * as pulumi from "@pulumi/pulumi";
import * as pulumiservice from "@pulumi/pulumiservice";
import * as random from "@pulumi/random";

export = async () => {

    const orgName = pulumi.getOrganization();
    const teamName = "team-1";
    const pipelineName = "coolspot";

    const tokenSuffix = new random.RandomString(`[${pipelineName}]-pulumi-token-suffix`, {
        length: 7,
        lower: true,
        minLower: 3,
        numeric: true,
        minNumeric: 4,
        special: false,
        upper: false,
    });

    const pulumiToken = new pulumiservice.TeamAccessToken(`[${pipelineName}]-token`, {
        name: pulumi.interpolate`${pipelineName}-${tokenSuffix.result}`,
        organizationName: orgName,
        teamName: teamName.toLowerCase(),
        description: `Access token for '${pipelineName}' pipeline.`,
    }, { dependsOn: tokenSuffix, deleteBeforeReplace: true });

}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by komalali**
Fixes a regression introduced in #191, fixes the diff functions for team tokens and org tokens to correctly replace on changes and adds tests.

Also fixed a bug in teams where an update was detected based on the order of team members.

Fixes #159
Fixes #158

### CODE REVIEW

File: provider/pkg/provider/access_token.go [hunk 1]
```diff
@@ -133,3 +133,35 @@ func (at *PulumiServiceAccessTokenResource) createAccessToken(ctx context.Contex
...
+	if err != nil {
+		return nil, err
+	}
+
+	news, err := plugin.UnmarshalProperties(req.GetNews(), plugin.MarshalOptions{KeepUnknowns: true, SkipNulls: false})
+	if err != nil {
+		return nil, err
+	}
+
+	diffs := olds["__inputs"].ObjectValue().Diff(news)
```
Comment (cleverguy25) [inline provider/pkg/provider/access_token.go:148]: Should we check for existence/nil here?

**Review by cleverguy25 — APPROVED** [review]
